export default {
  distro: {
    family: 'payload-postgres-starter',
    id: 'render-postgres-starter',
    label: 'Render-ready Payload Postgres Starter',
    runtime: {
      cloudflareEdgeSensitive: false,
      frontendScaffoldingAllowed: true,
      nodeDevScriptsAllowed: true,
      workerServerClientBoundaries: false,
    },
  },
  generators: {
    defaultHeaderComment: 'Generated by local scaffolder. Safe to edit unless otherwise documented.',
    preferPlopFor: ['collection', 'global'],
  },
  paths: {
    collectionsDir: 'src/cms/collections',
    collectionsIndex: 'src/cms/collections/index.ts',
    fieldsDir: 'src/cms/fields',
    fieldsIndex: 'src/cms/fields/index.ts',
    blocksDir: 'src/cms/blocks',
    blocksIndex: 'src/cms/blocks/index.ts',
    blockComponentsDir: 'src/components/blocks',
    blockRegistry: 'src/components/blocks/registry.tsx',
    blockComponentIndex: 'src/components/blocks/index.ts',
    globalsDir: 'src/cms/globals',
    globalsIndex: 'src/cms/globals/index.ts',
    plopfile: 'plopfile.cjs',
  },
  naming: {
    blockSlugCase: 'kebab',
    fieldNameCase: 'camel',
    rendererKeyCase: 'camel',
  },
  registration: {
    blockArrayName: 'PAGE_BLOCKS',
    blockRegistryObjectName: 'BLOCK_RENDERERS',
  },
}
