import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const defaultConfig = {
  distro: {
    family: 'payload-postgres-starter',
    id: 'unknown-payload-distro',
    label: 'Unknown Payload Distro',
    runtime: {
      cloudflareEdgeSensitive: false,
      frontendScaffoldingAllowed: false,
      nodeDevScriptsAllowed: true,
      workerServerClientBoundaries: false,
    },
  },
  generators: {
    defaultHeaderComment: 'Generated by local scaffolder. Safe to edit unless otherwise documented.',
    preferPlopFor: [],
  },
  paths: {
    collectionsDir: 'src/cms/collections',
    collectionsIndex: 'src/cms/collections/index.ts',
    fieldsDir: 'src/cms/fields',
    fieldsIndex: 'src/cms/fields/index.ts',
    blocksDir: 'src/cms/blocks',
    blocksIndex: 'src/cms/blocks/index.ts',
    blockComponentsDir: 'src/components/blocks',
    blockRegistry: 'src/components/blocks/registry.tsx',
    blockComponentIndex: 'src/components/blocks/index.ts',
    globalsDir: 'src/cms/globals',
    globalsIndex: 'src/cms/globals/index.ts',
    plopfile: 'plopfile.cjs',
  },
  naming: {
    blockSlugCase: 'kebab',
    fieldNameCase: 'camel',
    rendererKeyCase: 'camel',
  },
  registration: {
    blockArrayName: 'PAGE_BLOCKS',
    blockRegistryObjectName: 'BLOCK_RENDERERS',
  },
}

const envPathMappings = [
  ['SCAFFOLDER_COLLECTIONS_DIR', ['paths', 'collectionsDir']],
  ['SCAFFOLDER_COLLECTIONS_INDEX', ['paths', 'collectionsIndex']],
  ['SCAFFOLDER_GLOBALS_DIR', ['paths', 'globalsDir']],
  ['SCAFFOLDER_GLOBALS_INDEX', ['paths', 'globalsIndex']],
  ['SCAFFOLDER_FIELDS_DIR', ['paths', 'fieldsDir']],
  ['SCAFFOLDER_FIELDS_INDEX', ['paths', 'fieldsIndex']],
  ['SCAFFOLDER_BLOCKS_DIR', ['paths', 'blocksDir']],
  ['SCAFFOLDER_BLOCKS_INDEX', ['paths', 'blocksIndex']],
  ['SCAFFOLDER_BLOCK_COMPONENTS_DIR', ['paths', 'blockComponentsDir']],
  ['SCAFFOLDER_BLOCK_COMPONENTS_INDEX', ['paths', 'blockComponentIndex']],
  ['SCAFFOLDER_BLOCK_REGISTRY', ['paths', 'blockRegistry']],
  ['SCAFFOLDER_PLOPFILE', ['paths', 'plopfile']],
  ['SCAFFOLDER_BLOCK_ARRAY_NAME', ['registration', 'blockArrayName']],
  ['SCAFFOLDER_BLOCK_REGISTRY_OBJECT_NAME', ['registration', 'blockRegistryObjectName']],
]

const hasPath = (rootDir, relativePath) => fs.existsSync(path.join(rootDir, relativePath))

const inferDistroId = (rootDir) => {
  if (hasPath(rootDir, 'render.yaml')) return 'render-postgres-starter'
  if (hasPath(rootDir, 'vercel.json')) return 'vercel-payload-starter'
  if (hasPath(rootDir, 'wrangler.toml')) return 'cloudflare-payload-starter'
  return defaultConfig.distro.id
}

const setNestedValue = (target, pathParts, value) => {
  let current = target

  for (let index = 0; index < pathParts.length - 1; index += 1) {
    const part = pathParts[index]
    current[part] ??= {}
    current = current[part]
  }

  current[pathParts[pathParts.length - 1]] = value
}

const loadEnvOverrides = (env = process.env) => {
  const overrides = {}

  for (const [envName, pathParts] of envPathMappings) {
    const value = env[envName]
    if (!value) continue
    setNestedValue(overrides, pathParts, value)
  }

  return overrides
}

export const loadScaffolderAdapter = async (rootDir) => {
  const configPath = path.join(rootDir, 'scaffolder.config.mjs')
  const envOverrides = loadEnvOverrides(process.env)

  if (fs.existsSync(configPath)) {
    const loadedConfig = await import(`${pathToFileURL(configPath).href}?t=${Date.now()}`)
    const repoScaffolderConfig = loadedConfig.default ?? {}

    return {
      ...defaultConfig,
      ...repoScaffolderConfig,
      ...envOverrides,
      distro: {
        ...defaultConfig.distro,
        ...repoScaffolderConfig?.distro,
        ...envOverrides?.distro,
        runtime: {
          ...defaultConfig.distro.runtime,
          ...repoScaffolderConfig?.distro?.runtime,
          ...envOverrides?.distro?.runtime,
        },
      },
      generators: {
        ...defaultConfig.generators,
        ...repoScaffolderConfig?.generators,
        ...envOverrides?.generators,
      },
      paths: {
        ...defaultConfig.paths,
        ...repoScaffolderConfig?.paths,
        ...envOverrides?.paths,
      },
      naming: {
        ...defaultConfig.naming,
        ...repoScaffolderConfig?.naming,
        ...envOverrides?.naming,
      },
      registration: {
        ...defaultConfig.registration,
        ...repoScaffolderConfig?.registration,
        ...envOverrides?.registration,
      },
    }
  }

  return {
    ...defaultConfig,
    ...envOverrides,
    distro: {
      ...defaultConfig.distro,
      ...envOverrides?.distro,
      id: inferDistroId(rootDir),
      label: inferDistroId(rootDir),
    },
    generators: {
      ...defaultConfig.generators,
      ...envOverrides?.generators,
    },
    paths: {
      ...defaultConfig.paths,
      ...envOverrides?.paths,
    },
    naming: {
      ...defaultConfig.naming,
      ...envOverrides?.naming,
    },
    registration: {
      ...defaultConfig.registration,
      ...envOverrides?.registration,
    },
  }
}

export const summarizeAdapter = (adapter) => ({
  distro: adapter.distro.id,
  fieldsDir: adapter.paths.fieldsDir,
  collectionsDir: adapter.paths.collectionsDir,
  globalsDir: adapter.paths.globalsDir,
  blocksDir: adapter.paths.blocksDir,
  blockRegistry: adapter.paths.blockRegistry,
  blockComponentIndex: adapter.paths.blockComponentIndex,
  plopPreferred: adapter.generators.preferPlopFor,
  frontendScaffoldingAllowed: adapter.distro.runtime.frontendScaffoldingAllowed,
})
