import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const defaultConfig = {
  distro: {
    family: 'payload-postgres-starter',
    id: 'unknown-payload-distro',
    label: 'Unknown Payload Distro',
    runtime: {
      cloudflareEdgeSensitive: false,
      frontendScaffoldingAllowed: false,
      nodeDevScriptsAllowed: true,
      workerServerClientBoundaries: false,
    },
  },
  generators: {
    defaultHeaderComment: 'Generated by local scaffolder. Safe to edit unless otherwise documented.',
    preferPlopFor: [],
  },
  paths: {
    collectionsDir: 'src/cms/collections',
    collectionsIndex: 'src/cms/collections/index.ts',
    fieldsDir: 'src/cms/fields',
    fieldsIndex: 'src/cms/fields/index.ts',
    blocksDir: 'src/cms/blocks',
    blocksIndex: 'src/cms/blocks/index.ts',
    blockComponentsDir: 'src/components/blocks',
    blockRegistry: 'src/components/blocks/registry.tsx',
    blockComponentIndex: 'src/components/blocks/index.ts',
    globalsDir: 'src/cms/globals',
    globalsIndex: 'src/cms/globals/index.ts',
    plopfile: 'plopfile.cjs',
  },
  naming: {
    blockSlugCase: 'kebab',
    fieldNameCase: 'camel',
    rendererKeyCase: 'camel',
  },
  registration: {
    blockArrayName: 'PAGE_BLOCKS',
    blockRegistryObjectName: 'BLOCK_RENDERERS',
  },
}

const hasPath = (rootDir, relativePath) => fs.existsSync(path.join(rootDir, relativePath))

const inferDistroId = (rootDir) => {
  if (hasPath(rootDir, 'render.yaml')) return 'render-postgres-starter'
  if (hasPath(rootDir, 'vercel.json')) return 'vercel-payload-starter'
  if (hasPath(rootDir, 'wrangler.toml')) return 'cloudflare-payload-starter'
  return defaultConfig.distro.id
}

export const loadScaffolderAdapter = async (rootDir) => {
  const configPath = path.join(rootDir, 'scaffolder.config.mjs')

  if (fs.existsSync(configPath)) {
    const loadedConfig = await import(`${pathToFileURL(configPath).href}?t=${Date.now()}`)
    const repoScaffolderConfig = loadedConfig.default ?? {}

    return {
      ...defaultConfig,
      ...repoScaffolderConfig,
      distro: {
        ...defaultConfig.distro,
        ...repoScaffolderConfig?.distro,
        runtime: {
          ...defaultConfig.distro.runtime,
          ...repoScaffolderConfig?.distro?.runtime,
        },
      },
      generators: {
        ...defaultConfig.generators,
        ...repoScaffolderConfig?.generators,
      },
      paths: {
        ...defaultConfig.paths,
        ...repoScaffolderConfig?.paths,
      },
      naming: {
        ...defaultConfig.naming,
        ...repoScaffolderConfig?.naming,
      },
      registration: {
        ...defaultConfig.registration,
        ...repoScaffolderConfig?.registration,
      },
    }
  }

  return {
    ...defaultConfig,
    distro: {
      ...defaultConfig.distro,
      id: inferDistroId(rootDir),
      label: inferDistroId(rootDir),
    },
  }
}

export const summarizeAdapter = (adapter) => ({
  distro: adapter.distro.id,
  fieldsDir: adapter.paths.fieldsDir,
  collectionsDir: adapter.paths.collectionsDir,
  blocksDir: adapter.paths.blocksDir,
  blockRegistry: adapter.paths.blockRegistry,
  blockComponentIndex: adapter.paths.blockComponentIndex,
  plopPreferred: adapter.generators.preferPlopFor,
  frontendScaffoldingAllowed: adapter.distro.runtime.frontendScaffoldingAllowed,
})
