import { PERMISSIONS, PERMISSION_VALUES, type Permission } from './permissions'

export const ROLES = {
  SUPER_ADMIN: 'super-admin',
  ADMIN: 'admin',
  EDITOR: 'editor',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const ROLE_VALUES = Object.values(ROLES) as Role[]

export const ROLE_PRESETS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: PERMISSION_VALUES,
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.MEDIA_ACCESS,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE,
    PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.PAGES_ACCESS,
    PERMISSIONS.PAGES_CREATE,
    PERMISSIONS.PAGES_UPDATE,
    PERMISSIONS.PAGES_DELETE,
    PERMISSIONS.POSTS_ACCESS,
    PERMISSIONS.POSTS_CREATE,
    PERMISSIONS.POSTS_UPDATE,
    PERMISSIONS.POSTS_DELETE,
    PERMISSIONS.REDIRECTS_ACCESS,
    PERMISSIONS.REDIRECTS_CREATE,
    PERMISSIONS.REDIRECTS_UPDATE,
    PERMISSIONS.REDIRECTS_DELETE,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
  ],
  [ROLES.EDITOR]: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.MEDIA_ACCESS,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE_OWN,
    PERMISSIONS.MEDIA_DELETE_OWN,
    PERMISSIONS.PAGES_ACCESS,
    PERMISSIONS.PAGES_CREATE,
    PERMISSIONS.PAGES_UPDATE_OWN,
    PERMISSIONS.PAGES_DELETE_OWN,
    PERMISSIONS.POSTS_ACCESS,
    PERMISSIONS.POSTS_CREATE,
    PERMISSIONS.POSTS_UPDATE_OWN,
    PERMISSIONS.POSTS_DELETE_OWN,
  ],
}
